const path = require("path");

const logDir = path.join(__dirname, "logs", "prod");

module.exports = {
  apps: [
    {
      name: "NLC-CMS",
      script: "server/server.js",
      exec_mode: "cluster",
      instances: 2,
      watch: false,
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      max_memory_restart: "800M",
      restart_delay: 4000,
      env: {
        NODE_ENV: "production",
        PORT: 443,
        HTTP_PORT: 80,
        HOST: "0.0.0.0",
        HTTPS_ENABLED: "true",
        SSL_KEY_PATH: "config/ssl/server.key",
        SSL_CERT_PATH: "config/ssl/server.crt",
        SSL_CA_PATH: "config/ssl/ca-bundle.crt",
        DATABASE_URL: "postgresql://fixsmart:mrbunny22@199.199.50.51:5432/kochicms?schema=test4",
        JWT_SECRET: "dasjkdfsgfjsdhgfjsjkfvbbxdhwiuiq154654646",
        JWT_EXPIRE: "7d",
        CLIENT_URL: "https://0.0.0.0",
        CORS_ORIGIN: "https://0.0.0.0,http://0.0.0.0,https://localhost,http://localhost",
        TRUST_PROXY: "true",
        RATE_LIMIT_WINDOW_MS: "900000",
        RATE_LIMIT_MAX: "1000",
        MAX_FILE_SIZE: "10485760",
        UPLOAD_PATH: "./uploads",
        EMAIL_SERVICE: "smtp.office365.com",
        EMAIL_USER: "swsm@cimconautomation.com",
        EMAIL_PASS: "cimcon@1987",
        EMAIL_PORT: "587",
        EMAIL_FROM: "Cochin Smart City",
        HELMET_CSP_ENABLED: "true",
        LOG_LEVEL: "info",
        LOG_FILE: "logs/application.log",
        ENABLE_METRICS: "true",
        DATABASE_POOL_MIN: "2",
        DATABASE_POOL_MAX: "10"
      },
      env_https: {
        NODE_ENV: "production",
        PORT: 443,
        HTTP_PORT: 80,
        HOST: "0.0.0.0",
        HTTPS_ENABLED: "true",
        SSL_KEY_PATH: "config/ssl/server.key",
        SSL_CERT_PATH: "config/ssl/server.crt",
        SSL_CA_PATH: "config/ssl/ca-bundle.crt",
        DATABASE_URL: "postgresql://fixsmart:mrbunny22@199.199.50.51:5432/kochicms?schema=test4",
        JWT_SECRET: "dasjkdfsgfjsdhgfjsjkfvbbxdhwiuiq154654646",
        JWT_EXPIRE: "7d",
        CLIENT_URL: "https://0.0.0.0",
        CORS_ORIGIN: "https://0.0.0.0,http://0.0.0.0,https://localhost,http://localhost",
        TRUST_PROXY: "true",
        RATE_LIMIT_WINDOW_MS: "900000",
        RATE_LIMIT_MAX: "1000",
        MAX_FILE_SIZE: "10485760",
        UPLOAD_PATH: "./uploads",
        EMAIL_SERVICE: "smtp.office365.com",
        EMAIL_USER: "swsm@cimconautomation.com",
        EMAIL_PASS: "cimcon@1987",
        EMAIL_PORT: "587",
        EMAIL_FROM: "Cochin Smart City",
        HELMET_CSP_ENABLED: "true",
        LOG_LEVEL: "info",
        LOG_FILE: "logs/application.log",
        ENABLE_METRICS: "true",
        DATABASE_POOL_MIN: "2",
        DATABASE_POOL_MAX: "10"
      },
      out_file: path.join(logDir, "api-out.log"),
      error_file: path.join(logDir, "api-error.log"),
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      kill_timeout: 5000,
      listen_timeout: 8000,
      wait_ready: true,
    },
  ],
};
